# Pull DOTNET 6 SDK from microsoft registry
FROM mcr.microsoft.com/dotnet/sdk:6.0 as BUILD_DEVELOPMENT
WORKDIR /apis/OpenEcommerceCore

# Copy project
COPY ../../apis/OpenEcommerceCore .

# Build the app
RUN dotnet restore

RUN dotnet publish --no-restore -c Debug -o /app

# PULL ASPNET 6 Runtime from Microsoft Registry
FROM mcr.microsoft.com/dotnet/aspnet:6.0 as RUNTIME

# Copy Build to Working Directory
WORKDIR /app
COPY --from=BUILD_DEVELOPMENT /app ./

# Set Entrypoint to run application
ENTRYPOINT [ "dotnet", "Core.Api.dll" ]