services:
  dev-api:
    build: .
    depends_on:
      - dev-postgres-db
      - azurite-emulator
    ports:
      - "8081:5001"
      - "8080:5000"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - BLOB_CLIENT_STORAGE_CONNECTION_STRING
      - STOCK_POSTGRES_DATABASE
      - USER_ACCESS_POSTGRES_DATABASE
      - USER_ACCESS_DERIVATION_SECURITY_KEY
      - USER_ACCESS_JWT_SECURITY_KEY
      - STOCK_MODULE_ADMINISTRATIVE_DASHBOARD_URL

  dev-postgres-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  azurite-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
