services:
  dev-api:
    env_file:
      - .env
    container_name: Core-API-0
    build: .
    depends_on:
      - dev-postgres-db
      - azurite-emulator
    ports:
      - "8080:80/tcp"
  dev-postgres-db:
    container_name: Core-Postgres-0
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - /var/coreapi/postgres:/var/lib/postgresql/data:rw

  azurite-emulator:
    container_name: Core-Azurite-0
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
    env_file:
      - .env
    volumes:
      - /var/coreapi/azurite:/var/lib/azurite/data:rw
